### ISSUE TITLE
Switch language "on the fly"

### ISSUE THREAD

**Issue by eonlab** [codezero-be/laravel-localized-routes#23] opened 2020-01-20 13:23 UTC
I've made a dropdown to switch the language but it didn't work "on the fly", only after clicking the link twice the page loaded with the selected language. I was able to do it by replacing the SetLocale middleware and adding to the handle function: 

App::setLocale($locale);
Carbon::setLocale($locale);
Date::setLocale($locale);

I don't know if anyone had the same problem but here's the solution I've found. 
Thanks, and great package by the way!

**Comment by ivanvermeyen** [comment] 2020-01-20 13:29
Hello and thanks for reporting!

Are you using the latest version?
I've fixed a number of bugs in the `Route::localizedUrl()` lately.

Is the `Carbon` and `Date` setLocale relevant to your URL generation?
Could you share some code about the issue?

**Comment by ivanvermeyen** [comment] 2020-01-20 15:17
Weird... I can't reproduce it here.

When you register routes in the `Route::localized()` function, a `localized-routes-locale` key is added to that route to reference its locale. When accessing that route later, the key is found by the middleware and then passed to `LocaleHandler`, which sets it as the app locale.

If you set `use_localizer` to `true` the app locale should still be set, in addition to setting a cookie and saving it to the session. The special key in the route always has priority and will be used as the app locale if its present.

If `Route::localizedUrl()` generates the correct localized URL's it should just trigger the middleware and find the `localized-routes-locale` key in that route when that page loads...

**Comment by eonlab** [comment] 2020-01-20 15:59
I'm testing it on windows using Laragon  (Nginx + PHP7.2FastCGI). I didn't tested it on Linux.

**Comment by eonlab** [comment] 2020-01-21 13:48
Ok, I figure it out. I've installed Laravel-Admin with the multiple language plugin and it seems it conflicts with it and doesn't make the change "on the fly". When I switch the language in the frontend using this package it also switches the language in the admin

**Comment by ivanvermeyen** [comment] 2020-01-21 13:56
Which admin package are your referring to?
Did you find a way to solve the conflict?

**Comment by eonlab** [comment] 2020-01-21 14:56
I didn't solve it yet.

The admin package is this one:
https://github.com/z-song/laravel-admin
And the multiple language plugin is this:
https://github.com/laravel-admin-extensions/multi-language

**Comment by eonlab** [comment] 2020-01-21 16:52
Solved! It seems that the SESSION_DRIVER in the .env file on Laravel 6 was set to cookies, tried setting it to 'database' and it works.

**Comment by ivanvermeyen** [comment] 2020-01-21 17:28
`SESSION_DRVER` is set to `cookie` here too.
Not sure why it would make a difference tho.
But... if it works, it works I guess :)

**Comment by eonlab** [comment] 2020-01-21 17:40
I also changed the name of the locale cookie, on the admin multi-language plugin, both were named 'locale'

**Comment by ivanvermeyen** [comment] 2020-01-22 11:31
Since it's working and there is nothing I can do (I think?), I'll close this issue for now.
If you continue to experience problems with this, feel free to reopen! 👍

**Closed by ivanvermeyen** 2020-01-22 11:31 UTC
