### ISSUE TITLE
Localized routes throws 404 for default locale

### ISSUE THREAD

**Issue by Niekto350** [codezero-be/laravel-localized-routes#35] opened 2021-03-12 20:54 UTC
If you set `omit_url_prefix_for_locale` for your default locale, requesting valid url with that locale results in a 404.

For example:
https://myapp.dev/something/show/11 <- this works, en page is loaded
https://myapp.dev/en/something/show/11 <- this throws 404
https://myapp.dev/es/something/show/11 <- this works, es page is loaded
https://myapp.dev/de/something/show/11 <- this works, de page is loaded

You cannot control behavior of the users, therefore it should be as fool proof as possible and given that the user have provided a valid url, it should load that url. Seeing 404 may make the user believe it does not exist on the server so he leaves never to return.
If you don't set the setting `omit_url_prefix_for_locale` than the first url would throw 404.

Desired output is to load both versions of the url. If url without locale code is requested, all urls should be generated without locale and use that default locale behind the scenes. If url with any supported locale is requested, all urls should be generated with that locale.

Also I'm creating an application that is going to be heavily using localization including inputs from the user. Because of that I want to make it as obvious as possible which locale is currently loaded so I need to keep the locale part in the url if it was present in previous request. Saving forms using wrong locale would result in lost of data as data for different locale would be overwritten. But I don't want to be bothering users with it if it's not present in their original request.

BTW: Originally I had more detailed issue report but my tab has crashed and I've lost it. If something is not clear or you need some more information, I'm happy to help.

**Comment by ivanvermeyen** [comment] 2021-03-13 12:05
Hi,

Thanks for the feedback!

Can your use case be compared with #18 ?
I am planning to improve this kind of behavior, but I don't have an ETA at the moment.
There is a [workaround in the comments](https://github.com/codezero-be/laravel-localized-routes/issues/18#issuecomment-682576447) that might be helpful.

**Comment by Niekto350** [comment] 2021-03-13 17:26
Hello, thanks for a quick reply. Yes it's similar even thou not exactly the same. Ideally the response would not be force redirected to the localized url, keeping the url without the locale if it was requested without it and only serving the default locale behind the scenes.

Regarding the workaround solution, yes it's working, haven't found anything problematic so far except that the url is force redirected to the localized version. It's however acceptable middle ground if logic I've described in the previous paragraph would be problematic to implement.

**Comment by xewl** [comment] 2021-03-21 14:46
You shouldn't allow for double content (SEO).
Thus redirecting them to the "canonical"-URL when hitting the default language is a fair use case imho.

**Comment by Niekto350** [comment] 2021-03-24 20:56
Well it depends on a user, some are complaining if the url is containing that "unnecessary" locale segment. I personally like it there as it put the emphasis on the locale so it's additional indication which locale is active therefore contributing to prevent some data being overwritten by accident.

By the way, we are talking about application behind authentication middleware so SEO does not play a role here.

**Comment by mgralikowski** [comment] 2021-04-14 10:48
My vote is on behavior with redirecting to any language, so example.com should always redirect to example.com/LANG where LANG is taken from the session, browser, etc.

For now, without using `omit_url_prefix_for_locale`, the default page URL (example.com) returns 404, what is strange for me. I use https://github.com/codezero-be/laravel-localized-routes/issues/18#issuecomment-682576447 to fix it.

**Comment by ivanvermeyen** [comment] 2021-04-14 11:34
@mgralikowski I left the homepage "/" up to the developer, because maybe you want to show a language selection page instead. It's also easy enough to add a redirect to the detected locale.
But maybe I can make it the default behavior if a redirect option is set and no home route is explicitly registered.

I'm currently making a list of all possible options/behaviors.

**Comment by mgralikowski** [comment] 2021-04-14 11:51
Hm, but the problem is not only with the home page but all routes.
E.g. example.com/sub-page should redirect to example.com/LANG/sub-page
It is a nice feature for redactors, marketers who don't know yet, what is the client's language of receivers of email, ads.

About selecting language, In most cases, a language switcher is a page widget on the header/footer. It is a long time when I have seen the full-page language selector last time.

**Comment by ivanvermeyen** [comment] 2021-04-14 12:25
@mgralikowski Yes, sorry, I was reacting to your mention of the home page redirect, but I would implement this for alle pages. And I would only redirect if the option is set and the route in question is not explicitly registered.

So if you would register "site.com/something" outside of the localized closure, that page would no longer redirect to "site.com/en/something" for example. 

I agree with the language switcher being a widget on every page, but I like to keep it as flexible as possible.

**Comment by ivanvermeyen** [comment] 2021-04-16 18:21
Hello,

I've implemented the redirect feature in the following ways:

- you register a fallback route with a provided controller ([see docs](https://github.com/codezero-be/laravel-localized-routes#-localized-404-pages-and-redirecting-to-localized-urls))
- you enable `redirect_to_localized_urls` in the config file

Then:

- unprefixed URL's will redirect to the localized version (if it exists)
- this will redirect to whatever the app locale is, so you can apply the `SetLocale` middleware to the fallback route to use the user's preferred locale from the session or browser etc.
- if an unprefixed URL is a registered route, no redirect will happen
- or if omit the main locale, only URL's containing the main locale will redirect to the unprefixed version

The only use case I did not yet support is having both prefixed routes + an unprifexed for a main locale (without any redirect). But I'm not sure if this is actually needed?

**Comment by ivanvermeyen** [comment] 2021-04-17 13:21
Ok, so the complication with having both prefixed and unprefixed routes is that they both have to be registered.

How do you name them? If you have for example `about` and `en.about` and `nl.about` then you can no longer use `route('about')` to get a localized URL (it will return the `about` route).

Obviously, you also can not have duplicate names like `en.about`.

The only way I currently see to achieve this, is to change the `supported-locales` config, so you can optionally map a custom route prefix to a locale. Then you could make 2 english `about` routes with different prefixes, setting one as the omitted prefix/locale. This may have significant implications on the current code though.

If anyone has better ideas about this, I'd be happy to hear them :)

I'll keep this idea in the back of my head for now and release the current improvements.

**Comment by ivanvermeyen** [comment] 2021-04-17 13:28
Tagged and released in 2.5.0 🎉

**Closed by ivanvermeyen** 2021-04-17 13:28 UTC
